version: '3.8'

services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
